### ISSUE TITLE
Youtube Device Support

### ISSUE THREAD

**Issue by Oozemeister** [TheCrittaC/BigBen#40]
.yt is no longer supported, and only prints out this link. https://www.youtube.com/watch?v=UKY3scPIMd8

**Comment by TheCrittaC** [comment]
Thanks for reminding me, I'll try to fix it some time this week or next.

**Comment by TheCrittaC** [comment]
This is now fixed. The new approach is to do a web search for the specified title, then retrieve the first result. This way, no API key is required.
