### ISSUE TITLE
Broken /modules/pubmsg/__init__.py

### ISSUE THREAD

**Issue by Oozemeister** [TheCrittaC/BigBen#41]
".help" : "help" needs a comma added afterward ;)

**Comment by pixel5** [comment]
Proceding commas for last-child elements in PHP are a convention for many frameworks, but I don't know about Python. Does it cause a syntax error? If not, I support this convention. 

    `myVars = {
        "key1": 1,
        "key2": 2,
        "key3": 3,
    }`

**Comment by TheCrittaC** [comment]
This issue was fixed with the merging of your quote module. This does work, as seen with the __help__ and __commands__ variables in __init__.py.
